### ISSUE TITLE
Update path of files to relative in error message for Replay mode conversation

### ISSUE THREAD

**Issue by YauheniyaH** [epam/ai-dial-adapter-openai#135]
Currently, when create Replay for chat with broken files ( deleted or incorrect format), error message contain absolute path to the file
![image](https://github.com/user-attachments/assets/9d047a64-949d-43ed-9a94-7f0196badd96)

Error message format can be following:

> The following file attachments failed to process:
> 1. public/elephant.png: failed to download the attachment
> 2. public/business_tech_...ico: the attachment is not one of the supported types

or without public/ part

**Comment by VolhaBazhkova** [comment]
Fixed on staging, example,

![Image](https://github.com/user-attachments/assets/dd56a531-4f1b-413b-b5b1-205a8a3c6238)
