### ISSUE TITLE
Support function call parameters

### ISSUE THREAD

**Issue by avavilau** [epam/ai-dial-adapter-openai#22]
See https://platform.openai.com/docs/api-reference/chat  function_call

**Comment by vladisavvv** [comment]
Temporary solution:

If the clients set `functions` or `function_call` params and use api-version >= `2023-07-01` then we use them api-version for request instead of $AZURE_API_VERSION.

**Comment by vladisavvv** [comment]
@avavilau it's available in 0.2.0 release
