### ISSUE TITLE
Correct token calculation for streaming in case of using functions

### ISSUE THREAD

**Issue by vladisavvv** [epam/ai-dial-adapter-openai#29]
Currently we don't calculate tokens for functions and tools

**Comment by adubovik** [comment]
1. Consider enabling [stream_options.include_usage=True](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options)
2. Keep in mind that to this day we don't how to count tokens for tools/functions [presicely](https://github.com/langchain-ai/langchain/blob/ee579c77c1691bdf6b39aef649e1570516917e28/libs/partners/openai/langchain_openai/chat_models/base.py#L772-L801)

**Comment by adubovik** [comment]
Just in case: there is an unofficial function tokenizer, which assumes that OpenAI converts functions to TypeScript definitions: https://github.com/rubenselander/openai-function-tokens

**Comment by adubovik** [comment]
https://github.com/epam/ai-dial-adapter-openai/pull/170 estimates token count of function by tokenizing tools config serialized to a string. It's obviously not an exact match to the OpenAI tokenization, and it may **overestimate** as well as **underestimate** the token count, but it's still better than returning 0 completion tokens on a function call.

**Use with caution**. The recommended way is still using [stream_options.include_usage=True](https://platform.openai.com/docsapi-reference/chat/create#chat-create-stream_options) that provides the precise token count coming from Azure OpenAI.
